services:
  web:
    build:
      context: .
      args:
        DEV: "true"
    container_name: task_manager_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    container_name: task_manager_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: task_manager_user
      POSTGRES_PASSWORD: task_manager_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task_manager_user -d task_manager"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: